// Generated by devices/scripts/export-nexting-devices.mjs
// This root package makes the public host SDK installable directly from
// github.com/Nexting-ai/nexting.

// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Nexting",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "NextingDeviceKit", targets: ["NextingDeviceKit"]),
    ],
    targets: [
        .target(
            name: "NextingDeviceKit",
            path: "devices/sdk/swift/Sources/NextingDeviceKit"
        ),
        .testTarget(
            name: "NextingDeviceKitTests",
            dependencies: ["NextingDeviceKit"],
            path: "devices/sdk/swift/Tests/NextingDeviceKitTests"
        ),
    ]
)
